version: '3'
services:
  Database:
    image:  mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --default-time-zone=+05:30
    environment:
      MYSQL_ROOT_PASSWORD: rootcore@123
      MYSQL_DATABASE: DataManagement
      MYSQL_USER: User1
      MYSQL_PASSWORD: basecase
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"